### ISSUE TITLE
Contributing back

### ISSUE THREAD

**Issue by zommerfelds** [johnagan/serverless-slack#4]
Hi,

@bdcrouchman worked on a few improvements for this library (currently private).

- The bot.reply() function should not return a promise that ALWAYS rejects (currently expects data.ok === 'ok' but data === 'ok', so it rejects the promise)
- Expose the callback passed to the lambda. Without it isn't possible to have user issued commands show up in slack (without having the bot respond, but this causes the Slack bot to say it and the channel to look one-sided and ugly)
- Replying forcibly hides the slack response to http requests. This information is potentially useful. (swapped to using callback)
- Add errorstack config to the lambda handler. Currently gives no feedback when it crashes. Makes debugging more challenging.
- Other minor things

Let me know if you are interested and I can create a PR with all his changes.

**Comment by johnagan** [comment]
Thanks @zommerfelds 😎  If you've already done the work, I'm open to reviewing a PR. I'm purposely keeping this as generic as possible because it's meant to be a starting point, but if you've got some gems in yours I'm game for added them.

**Comment by diegopamio** [comment]
Do you have any fork where we can get these improvements?

**Comment by zommerfelds** [comment]
Hi all. Sorry I didn't answer back then! :( Unfortunately, I am no longer in possession of those changes. I must have left then with my previous company. I could ask my former colleagues if they still have the changes but I feel like it might be too much trouble for the actual content I had if it's not outdated.

@diegopamio if you are very keen, reopen and I can ask :)
