### ISSUE TITLE
How to send a delayed reply?

### ISSUE THREAD

**Issue by timidri** [johnagan/serverless-slack#5]
Hi @johnagan ,

I am trying to implement a slash command which executes a query taking longer than 3 seconds. Slack API docs (https://api.slack.com/slash-commands#responding_to_a_command) mention a way to use delayed responses. Can you give an example how to achieve this with serverless-stack? Thanks in advance!

**Comment by johnagan** [comment]
hmm.. Maybe check this project out? https://github.com/johnagan/serverless-slackbot

**Comment by timidri** [comment]
@johnagan Thanks, just checked it out, but still unclear how I would go about sending a delayed response? BTW are you saying it's not possible using serverless-slack? Thank you for any pointers.

**Comment by johnagan** [comment]
@timidri you'll need to queue up your incoming payload and pass it to another process. 

Slack needs a response within 3 seconds, but they give you a `response_url` in the payload that's good for ~ 30 minutes and 5 calls. So you return a `status 200` and then use the `response_url` instead. Slack refers to this as [delayed responses](https://api.slack.com/slash-commands#responding_to_a_command).

I _believe_ that example I sent you uses SNS to queue up, but you could use anything really. This would be the case for serverless or standard webservers.

**Comment by timidri** [comment]
Hi @johnagan, 

Thank you for the explanation. I understand that I need to a) return 200 to slack immediately and b) emit an event which will be processed by an independent invocation of the lambda handler. Since I am still a noob in event handling + asynchronous programming, I have 2 questions:
1. How can I return 200 from a `slack.on(...)` handler? Will just a `reply` or `say` do that?
2. What is the best way to emit an event in either model (serverless-slack or serverless-bot)?
Thanks again.

**Comment by timidri** [comment]
Just to follow up: I got it working. I am still using the serverless-slack and basically do a lambda.invoke() call from the event handler to queue up. Thanks for all the info!

**Comment by VivinrajSundararaj** [comment]
@timidri @johnagan I am just working on serverless slack bot and my aim is also to send delayed response. I read this conversation and may i know how have you resolved returning 200 immediately using serverless-slack? Is it just bot.reply("ok!")?

**Comment by timidri** [comment]
@VivinrajSundararaj It has been a while, but you can peruse this code I got working almost years ago: https://gist.github.com/timidri/b0c95399455ffa5f8741b01f2e4699ce . Good luck!

**Comment by VivinrajSundararaj** [comment]
@timidri Thank you so much! Will check it out!
